### ISSUE TITLE
Spatial Migrations Not Working For Me

### ISSUE THREAD

**Issue by gordonbanderson** [rgeo/activerecord-mysql2spatial-adapter#1]
hi Daniel

I am having problems with getting spatial migrations to work with RGeo.  It is of course possible I have misunderstood something simple but I have not seen a fully worked example with migrations on the web.

As such I have created a skeleton rails app with one model at https://github.com/gordonbanderson/RGeo-Migration-Example/

To recreate the issue I am having clone the repository, configure database.yml, execute bundle install.  I then get the following error on running bundle exec rake db:migrate:

<code>
rgeo-example gordon$ bundle exec rake --trace  db:migrate
(in /Users/gordon/work/git/weboftalent/rgeoexamplapp/rgeo-example)
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate
==  CreatePhotographs: migrating ==============================================
-- create_table(:photographs, {:options=>"ENGINE=MyISAM"})
rake aborted!
An error has occurred, all later migrations canceled:

undefined method `line_string' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x103aefa48>
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/schema_definitions.rb:326:in`method_missing'
/Users/gordon/work/git/weboftalent/rgeoexamplapp/rgeo-example/db/migrate/20110208022206_create_photographs.rb:5:in `up_without_benchmarks'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:157:in`create_table'
/Library/Ruby/Gems/1.8/gems/mysql2-0.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:470:in `create_table'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:383:in`send'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:383:in `method_missing'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:359:in`say_with_time'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:359:in`say_with_time'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:379:in `method_missing'
/Users/gordon/work/git/weboftalent/rgeoexamplapp/rgeo-example/db/migrate/20110208022206_create_photographs.rb:3:in`up_without_benchmarks'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:312:in `send'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:312:in`migrate'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:312:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:395:in `__send__'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:395:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:537:in `migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:613:in`call'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:613:in `ddl_transaction'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:536:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:523:in `each'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:523:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:433:in `up'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/migration.rb:415:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-3.0.3/lib/active_record/railties/databases.rake:142
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in`load'
/usr/bin/rake:19
</code>

It looks to me that the extensions to active record with regards to migrations are not being picked up for some reason.  Have I included the right gems, or is there some other configuration that I am missing?

Regards

Gordon

**Comment by sridharraman** [comment]
Hi

I am facing the same problem. I am unable to run any spatial migration. I've tried geometry, multi_polygon. But I get the same error when I run rake db:migrate:
undefined method `geometry' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x0000000afdf480>

I have set the adapter in the database.yml file to mysql2spatial as well. But nothing seems to work.

What could be the cause of this problem?

**Comment by januszm** [comment]
@sridharraman please provide information about version of: Rails, mysql2spatial-adapter and Ruby (the latter might be irrelevant though)

**Comment by sridharraman** [comment]
rails (4.1.15)
activerecord-mysql2spatial-adapter (0.4.3)
ruby 2.2.1p85

**Comment by januszm** [comment]
Use this one: https://rubygems.org/gems/activerecord-mysql2spatial-adapter/versions/0.5.0.nonrelease
I've made this version for one of my production apps, works fine.

**Comment by sridharraman** [comment]
Thanks @januszm. That works.

**Comment by januszm** [comment]
Unfortunately I don't have time to work on support for Rails 4.2 and 5.0 at the moment and I can't guarantee that it will happen anytime soon.
