### ISSUE TITLE
Support ActiveRecord 4.2

### ISSUE THREAD

**Issue by fjl82** [rgeo/activerecord-mysql2spatial-adapter#12]
The current version requires rgeo-activerecord 0.4.*, which does not work with AR 4.2:

```
E, [2014-12-23T09:54:57.557146 #3627] ERROR -- : undefined method `attribute_types_cached_by_default' for ActiveRecord::Base:Class (NoMethodError)
/var/lib/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/var/lib/gems/2.0.0/gems/rgeo-activerecord-0.4.6/lib/rgeo/active_record/common_adapter_elements.rb:159:in `<module:ActiveRecord>'
/var/lib/gems/2.0.0/gems/rgeo-activerecord-0.4.6/lib/rgeo/active_record/common_adapter_elements.rb:47:in `<module:RGeo>'
/var/lib/gems/2.0.0/gems/rgeo-activerecord-0.4.6/lib/rgeo/active_record/common_adapter_elements.rb:45:in `<top (required)>'
```

Please update the adapter to support newer versions of rgeo-activerecord.

**Comment by benatkin** [comment]
@fjl82 nice work!

@teeparham we're using this at @townsquared. I'm willing to start maintaining it. I would start just by merging @fjl82's change and making the test suite run on rails 4.2.

**Comment by teeparham** [comment]
@benatkin Hey good to hear from you! I added you to the rgeo organization. I'll add you as a gem owner so you can release new versions.

**Comment by benatkin** [comment]
@teeparham thanks! looking forward to getting this on travis-ci and cutting a new version.

**Comment by agoln** [comment]
@fjl82 - Thanks for making that port! I noticed at least one issue in my project, where the adapter didn't properly look up 'point' columns - it thought they were 'int'.  I sent you a pull request with https://github.com/fjl82/activerecord-mysql2spatial-adapter/pull/1.

**Comment by fjl82** [comment]
@agoln thanks for the fix, I merged the pull request. Looking forward to a new official release :)

**Comment by jdart** [comment]
+1 looking forward to new release.

**Comment by geniousli** [comment]
does it support in AR4.2?

**Comment by agodel** [comment]
Any updates on support for 4.2?

**Comment by dannyyu92** [comment]
+1

**Comment by dschweisguth** [comment]
@fjl82's fork works for me, with one additional change that fixes a NoMethodError when a table has a spatial index: https://github.com/dschweisguth/activerecord-mysql2spatial-adapter/commit/eced87fecec340284743a3d80eea453001b2ce88

**Comment by stephenq** [comment]
Will this ever get worked into a release?

**Comment by januszm** [comment]
Sorry guys, this project was shelved for some time because of lack of resources and support. If I understand correctly you'd like to go with flj82's fork with some patches like dschweisguth@eced87f ?

**Comment by dschweisguth** [comment]
That's working for me, so it would be helpful to me to have it on master. However, I don't have deep understanding of the code, I just made it work, so it's possible that a different solution would be better.

**Comment by fjl82** [comment]
Would be cool if this project received some real support again :) We rely on good geo support in our projects and I currently use my own fork in production (there's a branch for AR 5.0 also), but it's only provided on a "works for me" basis, since I don't have sufficient time to process bugreports.

I think I did take a look at dschweisguth's patch but I think I had some issue with it (don't remember what though). I do have one table with a spatial index and that works fine for me (a 'geometry' column).

**Comment by dschweisguth** [comment]
I have some time to work on this, but it isn't clear to me how to run the tests correctly. Judging from commit comments it looks like @januszm got the tests running on AR 4.1. What version(s) of Ruby work? What series of commands does one use to run the tests? So far the best I know how to do is

- use current Ruby
- ignore the Rakefile
- `gem build`
- `gem install`
- `ruby -Ilib -ractive_record/connection_adapters/mysql2spatial_adapter test/tc_basic.rb`

with which 5/12 tests fail. Any suggestions? @fjl82 you got the tests running on your branch, so maybe you know how too.

**Comment by fjl82** [comment]
@dschweisguth No sorry, I never got the tests running either. I was considering just leaving it for the moment, or rebuilding them from scratch, but I didn't have time for massive non-functional changes. I made my fork because we rely on this in our production system and didn't want to get stuck on an old version of Rails (running 5.1 now), but I have too many other things to work on to spend a lot of time on the tests.

**Comment by januszm** [comment]
@dschweisguth @fjl82 I'd be happy to merge your updates and provide support for newer AR versions. As I mentioned before, I can't actively work on new features at the moment so I can only provide you with information and code review.

To make the test suite running on Ruby 2.1 and ActiveRecord 4.1, first create database config file `test/database.yml`

```yaml
adapter: mysql2spatial
encoding: utf8
reconnect: true
host:     localhost
database: activerecord_test
username: root
password:
```

make sure the database exists, feel free to adjust credentials and database name.

This gem depends on 'rgeo-activerecord', '~> 1.0'. If you look at RGeo 1.x dependencies - it only works with `mysql2` gem versions 0.3.x. Make sure you have this gem installed, I'll push a new commit to master, that helps with installing correct version.

```bash
(master *) activerecord-mysql2spatial-adapter: bundle exec rake test
Loaded testcase test/tc_basic.rb
Loaded testcase test/tc_spatial_queries.rb
Run options: --seed 18312

# Running:

..............

Finished in 0.273528s, 51.1831 runs/s, 102.3662 assertions/s.

14 runs, 28 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by dschweisguth** [comment]
@januszm thanks for the info. The other thing breaking tests was a too-new version of rgeo. Tiny PR for the changes I made while getting the tests to pass: https://github.com/rgeo/activerecord-mysql2spatial-adapter/pull/22/files

I didn't add to the README to avoid conflicts with you, but if you'd prefer I do that just say so.

Next step is to add the appraisal gem and reapply @fjl82's and my changes to get AR 4.2 to work without breaking 4.1.

**Comment by dschweisguth** [comment]
I encountered one more issue getting the tests to run, filed #24, and fixed it in https://github.com/rgeo/activerecord-mysql2spatial-adapter/pull/23. I'll continue building on that towards 4.2 compatibility.

**Comment by januszm** [comment]
Thanks, I think that for future releases, we may just drop support for older AR versions ad clean up the code. Then we make it compatible with new AR and RGeo and bump the major gem version, those who need to work with older AR/rgeo will be able to still use adapter versions >= 0.5.0
