### PR TITLE
Upgrade Active Record dependency to 4.2 (not complete, in progress)

### LINKED ISSUE #12: Support ActiveRecord 4.2
The current version requires rgeo-activerecord 0.4.*, which does not work with AR 4.2:

```
E, [2014-12-23T09:54:57.557146 #3627] ERROR -- : undefined method `attribute_types_cached_by_default' for ActiveRecord::Base:Class (NoMethodError)
/var/lib/gems/2.0.0/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/var/lib/gems/2.0.0/gems/rgeo-activerecord-0.4.6/lib/rgeo/active_record/common_adapter_elements.rb:159:in `<module:ActiveRecord>'
/var/lib/gems/2.0.0/gems/rgeo-activerecord-0.4.6/lib/rgeo/active_record/common_adapter_elements.rb:47:in `<module:RGeo>'
/var/lib/gems/2.0.0/gems/rgeo-activerecord-0.4.6/lib/rgeo/active_record/common_adapter_elements.rb:45:in `<top (required)>'
```

Please update the adapter to support newer versions of rgeo-activerecord.

### PR DESCRIPTION
**Pull request by dschweisguth**
This PR intends to fix #12. It starts with a reapplication of the changes in https://github.com/fjl82/activerecord-mysql2spatial-adapter to current master.

To do:
- rebase after https://github.com/rgeo/activerecord-mysql2spatial-adapter/pull/23 is merged
- fix tests
- upgrade mysql2 dependency to 0.4.*, if that can be done without much extra work
- bump activerecord-mysql2spatial-adapter version, probably to 0.6.0

### CODE REVIEW

**Comment by januszm** [comment]
@dschweisguth I'd like to propose changes in baby steps, let's first add compatibility with newer rgeo , merge, and then let's focus on ActiveRecord 4.2

Also, things like code cleanup and .gitignore / Gemfile improvements we can do in a separate PR. It'll be easier to handle this and we'll deliver results in smaller increments, faster.

**Comment by dschweisguth** [comment]
I based this on the branch for my previous PR. Only the last commit here will remain after that other branch is merged and this one is rebased.

**Comment by guizmaii** [comment]
Any news ?

**Comment by januszm** [comment]
I think it's time to find a new maintainer for this project, I have not used this in my work for a long time.

I'll look at your new PR soon

**Comment by dschweisguth** [comment]
Other things are taking my time right now. I'll eventually get back to the project that uses this gem, but not very soon. Please do tell me if I should rebase anything of mine or test new releases of this gem against my project.
